version: '3'
services:
  postgres_db:
    container_name: ds_viz-db
    restart: always
    image: postgres:latest
    ports:
      - "3333:5432"
    environment:
      POSTGRES_DB: ds_viz_db
      POSTGRES_USER: ds_viz_user
      POSTGRES_PASSWORD: ds_viz_password_123
    networks: 
      - ds_viz_network

  ds_viz:
    container_name: ds_viz-backend-service
    restart: always
    image: ds_viz-fastapi
    ports:
      - "8889:8889"
    build: .
    expose:
      - "8889"
    volumes:
      - ./:/ds_viz/code
    depends_on:
      - postgres_db
    networks: 
      - ds_viz_network

networks: 
  ds_viz_network:
    driver: bridge
