version: '3'
services:
  postgres_db:
    container_name: ds_viz-db
    restart: always
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks: 
      - ds_viz_network

  ds_viz:
    container_name: ds_viz-backend-service
    restart: always
    image: ds_viz-fastapi
    ports:
      - "${DS_VIZ_PORT}:8889"
    build: .
    expose:
      - "${DS_VIZ_PORT}"
    volumes:
      - ./:/ds_viz/code
    depends_on:
      - postgres_db
    networks: 
      - ds_viz_network

  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4:latest
  #   restart: always
  #   environment:
  #       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #       PGADMIN_LISTEN_PORT: 80
  #   ports:
  #       - "${PGADMIN_PORT}:80"
  #   links:
  #       - "postgres_db:pgsql-server"
  #   volumes:
  #       - pgadmin-data:/var/lib/pgadmin
  #       - ./servers.json:/pgadmin4/servers.json   # Mount the servers.json file
  #   networks: 
  #     - ds_viz_network

networks: 
  ds_viz_network:
    driver: bridge

volumes:
    pgadmin-data:
