version: '3'
services:
  postgres_db:
    container_name: ds_viz-db
    image: postgres:latest
    ports:
      - "3333:5432"
    restart: always
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password

  ds_viz:
      container_name: ds_viz-backend-service
      restart: always
      image: ds_viz-fastapi
      ports:
        - "8889:8889"
      build: .
      expose:
        - "8889"
      volumes:
        - ./:/ds_viz/code # local dir is translate to leif_app/code in image file system
      depends_on:
        - postgres_db
      networks: 
        - my_network
        # uvicorn api:app --host 0.0.0.0 --port 8889 --reload

# https://medium.com/@shlomi.fenster1/setup-local-environment-for-postgresql-5531b8268397

#   pgadmin:
#     container_name: pgadmin4_container
#     image: dpage/pgadmin4
#     restart: always
#     environment:
#         PGADMIN_DEFAULT_EMAIL: shlomi@test.com
#         PGADMIN_DEFAULT_PASSWORD: 12345678
#         PGADMIN_LISTEN_PORT: 80
#     ports:
#         - "5050:80"
#     links:
#         - "db:pgsql-server"
#     volumes:
#         - pgadmin-data:/var/lib/pgadmin

# volumes:
#     pgadmin-data:
  
networks:
  my_network:
    driver: bridge
